target-folder: c


definitions:

- assignment-header: |
    ---
    title: "Aufgabenblatt ${sidx}"
    subtitle: "${subtitle}"
    ---

- assignment-solution-header: |
    ---
    title: "Lösungen zu Aufgabenblatt ${sidx}"
    subtitle: "${subtitle}"
    ---


jobs:

# 1. Statistische Daten
- assignment-paper:
  subtitle: "Statistische Daten"
  sol: 6ou3wer
  files: 
  - ${project-folder}/m-statistische-daten/aufgaben/*.qmd
- copy:
  from: ${project-folder}/m-statistische-daten/aufgaben/00-bilder
  to: ${target-folder}/00-bilder
- copy:
  from: ${project-folder}/m-statistische-daten/aufgaben/01-daten
  to: ${target-folder}/01-daten
- increment-index:

# 2. Einzelne Merkmale
- assignment-paper:
  subtitle: "Untersuchung einzelner Merkmale"
  sol: 834hja1
  files: 
  - ${project-folder}/m-einzelne-merkmale/aufgaben/*.qmd    
- increment-index:

# 3. Kenngrößen von Verteilungen
- assignment-paper:
  subtitle: "Kenngrößen von Verteilungen"
  sol: 348aiue
  files: 
  - ${project-folder}/m-kenngroessen/aufgaben/*.qmd    
- copy:
  from: ${project-folder}/m-kenngroessen/aufgaben/00-bilder
  to: ${target-folder}/00-bilder
  exclude-patterns: [".afdesign$"]
- increment-index:
