# In RStudio

Sie untersuchen Messdaten von einer Windkraftanlage in Dortmund (Forschungsprojekt an der Ruhr-Universit채t Bochum).

## Linienplot

Plotten Sie die Windgeschwindigkeit 체ber die Zeit in einem Linienplot (`geom_line()`). Welche der Merkmale `datum` oder `zeit` ist ihrer Meinung nach besser geeignet?

Zusatzfrage: Die Windgeschwindigkeit ist in Meter pro Sekunde angegeben. War es in dem Messzeitraum sehr windig?

## Streuplots

Stellen Sie folgende Zusammenh채nge in Streuplots dar:

-   Windgeschwindigkeit (`v_wind`) und Drehzahl (`drehzahl`).
-   Windgeschwindigkeit (`v_wind`) und Leistung (`leistung`).
-   Drehzahl (`drehzahl`) und Leistung (`leistung`).
-   Windgeschwindigkeit (`v_wind`) und Beschleunigung (`B6_y`).
-   Windgeschwindigkeit (`v_wind`) und Verformung (`w5`).

Berechnen Sie dabei jeweils den Korrelationskoeffizienten $r$ und plotten Sie die Regressionsgerade.

## Andere Darstellungsformen

Experimentieren Sie mit anderen Darstellungsformen (2D-Histogramm, Dichten) f체r den Zusammenhang zwischen Windgeschwindigkeit und Verformung.
