## Eigenschaften von Merkmalen

Eine Firma interessiert sich im Rahmen der Planung von Parkplätzen und dem Einsatz von firmeneigenen Bussen dafür, in welcher Entfernung ihre Beschäftigten von der Arbeitsstätte wohnen und mit welchen Beförderungsmitteln die Arbeitsstätte überwiegend erreicht wird. Sie greift dazu auf eine Untersuchung zurück, die zur Erfassung der wirtschaftlichen Lage der Mitarbeiterinnen und Mitarbeiter durchgeführt wurde. Bei der Untersuchung wurden an einem Stichtag 50 Beschäftige ausgewählt und befragt hinsichtlich

- Haushaltsgröße (Anzahl der im Haushalt lebenden Personen),
- monatliche Miete,
- Beförderungsmittel, mit dem die Arbeitsstätte überwiegend erreicht wird,
- Entfernung zwischen Wohnung und Arbeitsstätte,
- eigene Einschätzung der wirtschaftlichen Lage mit 1 = sehr gut, $\dots$ , 5 = sehr schlecht.

Aufgaben: 

1. Geben Sie die Grundgesamtheit und die statistischen Einheiten an.
1. Geben Sie für jedes Merkmal an,
    a) welche Ausprägungen es gibt und ob das Merkmal stetig oder diskret ist,
    a) welches Skalenniveau zugrunde liegt,
    a) ob es sich um ein qualitatives oder ein quantitatives Merkmal handelt.

Es bietet sich an, die Angaben in tabellarischer Form zusammenzustellen.

Quelle: Fahrmeir, L., Heumann, C., Künstler, R., Pigeot, I., & Tutz, G. (2016). Statistik, Der Weg zur Datenanalyse (8. Auflage).